apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: techtrends
  name: techtrends
  namespace: sandbox
spec:
  ports:
  - name: 4111-3111
    port: {{ .Values.image.port }}
    protocol: {{ .Values.image.protocol }}
    targetPort: {{ .Values.image.targetPort }}
  selector:
    app: techtrends
  type: {{ .Values.image.type }}
status:
  loadBalancer: {}
